// ============================================================
// 在這裡編輯你的活動內容 / Edit your activity content here
// ============================================================
//
// 【可選】想在照片中間穿插文字介紹，可以在任一活動物件裡加上
// "sections" 陣列，取代原本單純的照片牆。順序就是畫面上的順序，
// 文字段落跟照片群組可以自由交錯、重複幾次都可以。若不加這個欄
// 位，會照舊用 photos 陣列顯示成一整片照片牆。
//
// 格式範例（可直接複製貼到任一個活動物件裡，跟 photos 同一層）：
//
// sections: [
//   { type: "text", zh: "這裡放中文介紹段落。", en: "English intro paragraph here." },
//   { type: "photos", items: ["images/activity-1/1.jpg", "images/activity-1/2.jpg"] },
//   { type: "text", zh: "第二段文字，可以講活動的另一個環節。", en: "Second paragraph, e.g. about another part of the event." },
//   { type: "photos", items: ["images/activity-1/3.jpg", "images/activity-1/4.jpg", "images/activity-1/5.jpg"] }
// ],
//
// 只要照片檔名跟原本 images/activity-x/ 資料夾裡的一致即可，同一張
// 照片也可以分配到不同的 photos 群組裡，不用整批貼在一起。
//
// 【可選】想在頁面最上方（標題下方、照片牆之前）放一張置中的大合照
// （像首頁的精華影片那樣的明信片卡片樣式），在活動物件裡加上：
//
// groupPhoto: "images/activity-1/group.jpg",
//
// 把合照檔案放進對應的 images/activity-x/ 資料夾即可，檔名不限，
// 只要跟這裡填的路徑一致。不加這個欄位就不會顯示這個區塊。
// ============================================================

// 首頁主打影片的 YouTube 連結 (完整網址即可)
const HERO_VIDEO_URL = "https://youtu.be/tKBGch1f6Zs";

// 六場活動資料
const ACTIVITIES = [
  {
    id: 1,
    stamp: "NO. 01",
    date: "2026.03.12",
    titleZh: "大城市大冒險",
    titleEn: "Big City Adventure",
    descZh: "探索世界城市，攜手解決挑戰，展開一場冒險旅程。",
    descEn: "Explore cities, solve challenges, and discover the world together.",
    cover: "images/activity-1/cover.jpg",
    groupPhoto: "images/activity-1/group.jpg",
    photos: [
      "images/activity-1/1.jpg",
      "images/activity-1/2.jpg",
      "images/activity-1/3.jpg",
      "images/activity-1/4.jpg",
      "images/activity-1/5.jpg",
      "images/activity-1/6.jpg",
      "images/activity-1/8.jpg",
      "images/activity-1/9.jpg",
      "images/activity-1/10.jpg",
      "images/activity-1/12.jpg",
      "images/activity-1/14.jpg",
      "images/activity-1/15.jpg",
      "images/activity-1/16.jpg",
      "images/activity-1/17.jpg",
      "images/activity-1/18.jpg",
      "images/activity-1/19.jpg",
      "images/activity-1/20.jpg",
      "images/activity-1/21.jpg",
      "images/activity-1/22.jpg",
      "images/activity-1/23.jpg",
      "images/activity-1/24.jpg"
    ],
    sections: [
      { type: "text", zh: "每一座城市，都有一段等待被發現的故事。", en: "Every city has a story waiting to be discovered." },
      { type: "photos", items: ["images/activity-1/1.jpg", "images/activity-1/2.jpg", "images/activity-1/3.jpg", "images/activity-1/4.jpg", "images/activity-1/5.jpg"] },
      { type: "text", zh: "我們透過一道道挑戰，一步步探索世界。", en: "We explored the world one challenge at a time." },
      { type: "photos", items: ["images/activity-1/6.jpg", "images/activity-1/8.jpg", "images/activity-1/9.jpg", "images/activity-1/10.jpg"] },
      { type: "text", zh: "一起合作，讓每一場冒險都更加精彩。", en: "Working together made every adventure even more exciting." },
      { type: "photos", items: ["images/activity-1/12.jpg", "images/activity-1/14.jpg", "images/activity-1/15.jpg", "images/activity-1/16.jpg"] },
      { type: "text", zh: "每一次交流，都讓我們更靠近另一種文化。", en: "Every conversation brought us closer to a new culture." },
      { type: "photos", items: ["images/activity-1/17.jpg", "images/activity-1/18.jpg", "images/activity-1/19.jpg", "images/activity-1/20.jpg"] },
      { type: "text", zh: "每一段精彩的旅程，都始於一份好奇心。", en: "Great journeys always begin with curiosity." },
      { type: "photos", items: ["images/activity-1/21.jpg", "images/activity-1/22.jpg", "images/activity-1/23.jpg", "images/activity-1/24.jpg"] },
    ],
    videoUrls: []
  },
  {
    id: 2,
    stamp: "NO. 02",
    date: "2026.03.19",
    titleZh: "餅乾怪獸模式：啟動",
    titleEn: "Cookie Monster Mode: ON",
    descZh: "在烘焙與創作中，享受每一個充滿英語的甜蜜時刻。",
    descEn: "Bake, create, and enjoy English through every sweet moment.",
    cover: "images/activity-2/cover.jpg",
    groupPhoto: "images/activity-2/group.jpg",
    photos: [
      "images/activity-2/1.jpg",
      "images/activity-2/3.jpg",
      "images/activity-2/4.jpg",
      "images/activity-2/5.jpg",
      "images/activity-2/6.jpg",
      "images/activity-2/7.jpg",
      "images/activity-2/8.jpg",
      "images/activity-2/9.jpg",
      "images/activity-2/10.jpg",
      "images/activity-2/12.jpg",
      "images/activity-2/13.jpg",
      "images/activity-2/14.jpg",
      "images/activity-2/15.jpg",
      "images/activity-2/16.jpg",
      "images/activity-2/17.jpg",
      "images/activity-2/18.jpg",
      "images/activity-2/20.jpg",
      "images/activity-2/21.jpg",
      "images/activity-2/22.jpg",
      "images/activity-2/23.jpg",
      "images/activity-2/25.jpg",
      "images/activity-2/26.jpg",
      "images/activity-2/28.jpg",
      "images/activity-2/30.jpg",
      "images/activity-2/31.jpg",
      "images/activity-2/32.jpg",
      "images/activity-2/33.jpg",
      "images/activity-2/34.jpg",
      "images/activity-2/35.jpg",
      "images/activity-2/36.jpg",
      "images/activity-2/37.jpg",
      "images/activity-2/38.jpg",
      "images/activity-2/39.jpg",
      "images/activity-2/40.jpg",
      "images/activity-2/41.jpg",
      "images/activity-2/42.jpg",
      "images/activity-2/43.jpg",
      "images/activity-2/44.jpg",
      "images/activity-2/45.jpg",
      "images/activity-2/47.jpg",
      "images/activity-2/48.jpg",
      "images/activity-2/50.jpg"
    ],
    sections: [
      { type: "text", zh: "一起動手做餅乾，讓英文學習變得更加甜蜜。", en: "Baking together made English learning even sweeter." },
      { type: "photos", items: ["images/activity-2/1.jpg", "images/activity-2/3.jpg", "images/activity-2/4.jpg", "images/activity-2/5.jpg", "images/activity-2/6.jpg", "images/activity-2/7.jpg", "images/activity-2/8.jpg", "images/activity-2/9.jpg", "images/activity-2/10.jpg"] },
      { type: "text", zh: "每一塊餅乾，都充滿了創意與團隊合作。", en: "Every cookie was made with creativity and teamwork." },
      { type: "photos", items: ["images/activity-2/12.jpg", "images/activity-2/13.jpg", "images/activity-2/14.jpg", "images/activity-2/15.jpg", "images/activity-2/16.jpg", "images/activity-2/17.jpg", "images/activity-2/18.jpg", "images/activity-2/20.jpg", "images/activity-2/21.jpg"] },
      { type: "text", zh: "當大家享受每一刻時，學習也自然地發生。", en: "Learning happens naturally when everyone enjoys the moment." },
      { type: "photos", items: ["images/activity-2/22.jpg", "images/activity-2/23.jpg", "images/activity-2/25.jpg", "images/activity-2/26.jpg", "images/activity-2/28.jpg", "images/activity-2/30.jpg", "images/activity-2/31.jpg", "images/activity-2/32.jpg"] },
      { type: "text", zh: "分享美食，也是分享快樂的一種方式。", en: "Sharing food is another way of sharing happiness." },
      { type: "photos", items: ["images/activity-2/33.jpg", "images/activity-2/34.jpg", "images/activity-2/35.jpg", "images/activity-2/36.jpg", "images/activity-2/37.jpg", "images/activity-2/38.jpg", "images/activity-2/39.jpg", "images/activity-2/40.jpg"] },
      { type: "text", zh: "最甜美的回憶，總是在一起創造。", en: "The sweetest memories are always made together." },
      { type: "photos", items: ["images/activity-2/41.jpg", "images/activity-2/42.jpg", "images/activity-2/43.jpg", "images/activity-2/44.jpg", "images/activity-2/45.jpg", "images/activity-2/47.jpg", "images/activity-2/48.jpg", "images/activity-2/50.jpg"] },
    ],
    videoUrls: []
  },
  {
    id: 3,
    stamp: "NO. 03",
    date: "2026.04.23",
    titleZh: "從台灣與美國的日常標誌與廣告學英文",
    titleEn: "English through Everyday Signs and Ads in Taiwan and the USA",
    descZh: "從日常標誌與廣告中，發現英語就在我們身邊。",
    descEn: "Discover how English shapes our everyday lives.",
    cover: "images/activity-3/cover.jpg",
    groupPhoto: "images/activity-3/group.jpg",
    photos: [
      "images/activity-3/1.jpg",
      "images/activity-3/2.jpg",
      "images/activity-3/3.jpg",
      "images/activity-3/4.jpg",
      "images/activity-3/5.jpg",
      "images/activity-3/6.jpg",
      "images/activity-3/7.jpg",
      "images/activity-3/8.jpg",
      "images/activity-3/9.jpg",
      "images/activity-3/10.jpg",
      "images/activity-3/11.jpg",
      "images/activity-3/12.jpg",
      "images/activity-3/13.jpg",
      "images/activity-3/14.jpg",
      "images/activity-3/15.jpg",
      "images/activity-3/16.jpg",
      "images/activity-3/17.jpg",
      "images/activity-3/18.jpg",
      "images/activity-3/19.jpg",
      "images/activity-3/20.jpg",
      "images/activity-3/21.jpg",
      "images/activity-3/22.jpg",
      "images/activity-3/23.jpg",
      "images/activity-3/24.jpg",
      "images/activity-3/25.jpg",
      "images/activity-3/26.jpg",
      "images/activity-3/27.jpg",
      "images/activity-3/28.jpg",
      "images/activity-3/29.jpg",
      "images/activity-3/30.jpg",
      "images/activity-3/31.jpg",
      "images/activity-3/32.jpg",
      "images/activity-3/33.jpg",
      "images/activity-3/34.jpg",
      "images/activity-3/35.jpg",
      "images/activity-3/36.jpg",
      "images/activity-3/37.jpg",
      "images/activity-3/38.jpg",
      "images/activity-3/39.jpg",
      "images/activity-3/40.jpg"
    ],
    sections: [
      { type: "text", zh: "英文，其實就藏在我們的日常生活裡。", en: "English is hidden in our everyday surroundings." },
      { type: "photos", items: ["images/activity-3/1.jpg", "images/activity-3/2.jpg", "images/activity-3/3.jpg", "images/activity-3/4.jpg", "images/activity-3/5.jpg", "images/activity-3/6.jpg", "images/activity-3/7.jpg", "images/activity-3/8.jpg"] },
      { type: "text", zh: "每一個標誌，都訴說著文字背後的故事。", en: "Every sign tells a story beyond its words." },
      { type: "photos", items: ["images/activity-3/9.jpg", "images/activity-3/10.jpg", "images/activity-3/11.jpg", "images/activity-3/12.jpg", "images/activity-3/13.jpg", "images/activity-3/14.jpg", "images/activity-3/15.jpg", "images/activity-3/16.jpg"] },
      { type: "text", zh: "語言，讓我們用不同的角度看世界。", en: "Language helps us see the world from new perspectives." },
      { type: "photos", items: ["images/activity-3/17.jpg", "images/activity-3/18.jpg", "images/activity-3/19.jpg", "images/activity-3/20.jpg", "images/activity-3/21.jpg", "images/activity-3/22.jpg", "images/activity-3/23.jpg", "images/activity-3/24.jpg"] },
      { type: "text", zh: "微小的細節，往往帶來最有趣的發現。", en: "Small details often lead to meaningful discoveries." },
      { type: "photos", items: ["images/activity-3/25.jpg", "images/activity-3/26.jpg", "images/activity-3/27.jpg", "images/activity-3/28.jpg", "images/activity-3/29.jpg", "images/activity-3/30.jpg", "images/activity-3/31.jpg", "images/activity-3/32.jpg"] },
      { type: "text", zh: "當我們開始留意身邊的一切，學習便開始了。", en: "Learning begins when we start paying attention." },
      { type: "photos", items: ["images/activity-3/33.jpg", "images/activity-3/34.jpg", "images/activity-3/35.jpg", "images/activity-3/36.jpg", "images/activity-3/37.jpg", "images/activity-3/38.jpg", "images/activity-3/39.jpg", "images/activity-3/40.jpg"] },
    ],
    videoUrls: []
  },
  {
    id: 4,
    stamp: "NO. 04",
    date: "2026.04.29",
    titleZh: "從頭到腳：透過身體部位玩英語慣用語",
    titleEn: "From Head to Toe: Having Fun with English Idioms Through Body Parts",
    descZh: "透過遊戲與互動，讓英語慣用語變得生動有趣。",
    descEn: "Bring English idioms to life through games and interaction.",
    cover: "images/activity-4/cover.jpg",
    groupPhoto: "images/activity-4/group.jpg",
    photos: [
      "images/activity-4/1.jpg",
      "images/activity-4/2.jpg",
      "images/activity-4/3.jpg",
      "images/activity-4/4.jpg",
      "images/activity-4/5.jpg",
      "images/activity-4/6.jpg",
      "images/activity-4/7.jpg",
      "images/activity-4/8.jpg",
      "images/activity-4/9.jpg",
      "images/activity-4/10.jpg",
      "images/activity-4/11.jpg",
      "images/activity-4/12.jpg",
      "images/activity-4/13.jpg",
      "images/activity-4/14.jpg",
      "images/activity-4/15.jpg",
      "images/activity-4/16.jpg",
      "images/activity-4/17.jpg",
      "images/activity-4/19.jpg",
      "images/activity-4/20.jpg",
      "images/activity-4/21.jpg",
      "images/activity-4/22.jpg",
      "images/activity-4/23.jpg",
      "images/activity-4/25.jpg",
      "images/activity-4/26.jpg",
      "images/activity-4/27.jpg",
      "images/activity-4/29.jpg",
      "images/activity-4/30.jpg",
      "images/activity-4/31.jpg",
      "images/activity-4/32.jpg",
      "images/activity-4/33.jpg",
      "images/activity-4/34.jpg",
      "images/activity-4/36.jpg",
      "images/activity-4/37.jpg",
      "images/activity-4/38.jpg",
      "images/activity-4/39.jpg",
      "images/activity-4/40.jpg",
      "images/activity-4/41.jpg",
      "images/activity-4/42.jpg",
      "images/activity-4/43.jpg",
      "images/activity-4/44.jpg",
      "images/activity-4/46.jpg",
      "images/activity-4/47.jpg",
      "images/activity-4/48.jpg",
      "images/activity-4/50.jpg",
      "images/activity-4/51.jpg",
      "images/activity-4/52.jpg",
      "images/activity-4/53.jpg",
      "images/activity-4/54.jpg",
      "images/activity-4/58.jpg",
      "images/activity-4/60.jpg",
      "images/activity-4/61.jpg",
      "images/activity-4/62.jpg",
      "images/activity-4/63.jpg",
      "images/activity-4/65.jpg",
      "images/activity-4/66.jpg",
      "images/activity-4/67.jpg",
      "images/activity-4/68.jpg",
      "images/activity-4/69.jpg",
      "images/activity-4/70.jpg",
      "images/activity-4/71.jpg",
      "images/activity-4/72.jpg",
      "images/activity-4/73.jpg",
      "images/activity-4/74.jpg",
      "images/activity-4/75.jpg",
      "images/activity-4/76.jpg",
      "images/activity-4/77.jpg",
      "images/activity-4/78.jpg",
      "images/activity-4/80.jpg"
    ],
    sections: [
      { type: "text", zh: "慣用語讓日常英文變得更加生動有趣。", en: "Idioms make everyday English more lively and expressive." },
      { type: "photos", items: ["images/activity-4/1.jpg", "images/activity-4/2.jpg", "images/activity-4/3.jpg", "images/activity-4/4.jpg", "images/activity-4/5.jpg", "images/activity-4/6.jpg", "images/activity-4/7.jpg", "images/activity-4/8.jpg", "images/activity-4/9.jpg", "images/activity-4/10.jpg", "images/activity-4/11.jpg", "images/activity-4/12.jpg", "images/activity-4/13.jpg", "images/activity-4/14.jpg"] },
      { type: "text", zh: "每一句慣用語，背後都有一段有趣的故事。", en: "Every expression carries a story behind its meaning." },
      { type: "photos", items: ["images/activity-4/15.jpg", "images/activity-4/16.jpg", "images/activity-4/17.jpg", "images/activity-4/19.jpg", "images/activity-4/20.jpg", "images/activity-4/21.jpg", "images/activity-4/22.jpg", "images/activity-4/23.jpg", "images/activity-4/25.jpg", "images/activity-4/26.jpg", "images/activity-4/27.jpg", "images/activity-4/29.jpg", "images/activity-4/30.jpg", "images/activity-4/31.jpg"] },
      { type: "text", zh: "我們透過猜測、討論與歡笑一起學習。", en: "We learned by guessing, discussing, and laughing together." },
      { type: "photos", items: ["images/activity-4/32.jpg", "images/activity-4/33.jpg", "images/activity-4/34.jpg", "images/activity-4/36.jpg", "images/activity-4/37.jpg", "images/activity-4/38.jpg", "images/activity-4/39.jpg", "images/activity-4/40.jpg", "images/activity-4/41.jpg", "images/activity-4/42.jpg", "images/activity-4/43.jpg", "images/activity-4/44.jpg", "images/activity-4/46.jpg", "images/activity-4/47.jpg"] },
      { type: "text", zh: "當學習充滿樂趣，語言也更令人難忘。", en: "Language becomes unforgettable when learning is enjoyable." },
      { type: "photos", items: ["images/activity-4/48.jpg", "images/activity-4/50.jpg", "images/activity-4/51.jpg", "images/activity-4/52.jpg", "images/activity-4/53.jpg", "images/activity-4/54.jpg", "images/activity-4/58.jpg", "images/activity-4/60.jpg", "images/activity-4/61.jpg", "images/activity-4/62.jpg", "images/activity-4/63.jpg", "images/activity-4/65.jpg", "images/activity-4/66.jpg"] },
      { type: "text", zh: "一句簡單的慣用語，也能開啟自然的交流。", en: "A simple phrase can open the door to natural communication." },
      { type: "photos", items: ["images/activity-4/67.jpg", "images/activity-4/68.jpg", "images/activity-4/69.jpg", "images/activity-4/70.jpg", "images/activity-4/71.jpg", "images/activity-4/72.jpg", "images/activity-4/73.jpg", "images/activity-4/74.jpg", "images/activity-4/75.jpg", "images/activity-4/76.jpg", "images/activity-4/77.jpg", "images/activity-4/78.jpg", "images/activity-4/80.jpg"] },
    ],
    videoUrls: []
  },
  {
    id: 5,
    stamp: "NO. 05",
    date: "2026.05.07",
    titleZh: "跨越文化：一位南非人在台灣",
    titleEn: "Crossing Cultures: A South African in Taiwan",
    descZh: "分享故事、欣賞差異，建立跨文化的連結。",
    descEn: "Share stories, embrace differences, and build cultural connections.",
    cover: "images/activity-5/cover.jpg",
    groupPhoto: "images/activity-5/group.jpg",
    photos: [
      "images/activity-5/1.jpg",
      "images/activity-5/2.jpg",
      "images/activity-5/3.jpg",
      "images/activity-5/4.jpg",
      "images/activity-5/5.jpg",
      "images/activity-5/6.jpg",
      "images/activity-5/7.jpg",
      "images/activity-5/8.jpg",
      "images/activity-5/9.jpg",
      "images/activity-5/10.jpg",
      "images/activity-5/11.jpg",
      "images/activity-5/12.jpg",
      "images/activity-5/13.jpg",
      "images/activity-5/14.jpg",
      "images/activity-5/15.jpg",
      "images/activity-5/16.jpg",
      "images/activity-5/17.jpg",
      "images/activity-5/18.jpg",
      "images/activity-5/19.jpg",
      "images/activity-5/20.jpg",
      "images/activity-5/21.jpg",
      "images/activity-5/22.jpg",
      "images/activity-5/23.jpg",
      "images/activity-5/24.jpg",
      "images/activity-5/25.jpg"
    ],
    sections: [
      { type: "text", zh: "每一種文化，都提供了一種看待世界的新方式。", en: "Every culture offers a different way to see the world." },
      { type: "photos", items: ["images/activity-5/1.jpg", "images/activity-5/2.jpg", "images/activity-5/3.jpg", "images/activity-5/4.jpg", "images/activity-5/5.jpg"] },
      { type: "text", zh: "傾聽不同的故事，讓我們擁有更寬廣的視野。", en: "Listening to different experiences broadens our perspectives." },
      { type: "photos", items: ["images/activity-5/6.jpg", "images/activity-5/7.jpg", "images/activity-5/8.jpg", "images/activity-5/9.jpg", "images/activity-5/10.jpg"] },
      { type: "text", zh: "真誠的好奇心，是文化交流的起點。", en: "Cultural exchange begins with genuine curiosity." },
      { type: "photos", items: ["images/activity-5/11.jpg", "images/activity-5/12.jpg", "images/activity-5/13.jpg", "images/activity-5/14.jpg", "images/activity-5/15.jpg"] },
      { type: "text", zh: "真正的理解，往往從一場真誠的對話開始。", en: "Understanding each other starts with meaningful conversations." },
      { type: "photos", items: ["images/activity-5/16.jpg", "images/activity-5/17.jpg", "images/activity-5/18.jpg", "images/activity-5/19.jpg", "images/activity-5/20.jpg"] },
      { type: "text", zh: "不同的背景，反而讓彼此更加靠近。", en: "Different backgrounds bring us closer together." },
      { type: "photos", items: ["images/activity-5/21.jpg", "images/activity-5/22.jpg", "images/activity-5/23.jpg", "images/activity-5/24.jpg", "images/activity-5/25.jpg"] },
    ],
    videoUrls: []
  },
  {
    id: 6,
    stamp: "NO. 06",
    date: "2026.05.14",
    titleZh: "「字彙」三角：英語 X 日語 X 韓語",
    titleEn: "A \"Vocabulary\" Triangle: English X 日本語 X 한국어",
    descZh: "探索三種語言，發現跨越文化的共同連結。",
    descEn: "Explore three languages and discover connections across cultures.",
    cover: "images/activity-6/cover.jpg",
    groupPhoto: "images/activity-6/group.jpg",
    photos: [
      "images/activity-6/1.jpg",
      "images/activity-6/2.jpg",
      "images/activity-6/3.jpg",
      "images/activity-6/4.jpg",
      "images/activity-6/5.jpg",
      "images/activity-6/6.jpg",
      "images/activity-6/7.jpg",
      "images/activity-6/8.jpg",
      "images/activity-6/9.jpg",
      "images/activity-6/10.jpg",
      "images/activity-6/11.jpg",
      "images/activity-6/12.jpg",
      "images/activity-6/13.jpg",
      "images/activity-6/14.jpg",
      "images/activity-6/15.jpg",
      "images/activity-6/16.jpg",
      "images/activity-6/17.jpg",
      "images/activity-6/18.jpg",
      "images/activity-6/19.jpg",
      "images/activity-6/20.jpg",
      "images/activity-6/21.jpg",
      "images/activity-6/22.jpg",
      "images/activity-6/23.jpg",
      "images/activity-6/24.jpg",
      "images/activity-6/25.jpg",
      "images/activity-6/27.jpg",
      "images/activity-6/28.jpg",
      "images/activity-6/29.jpg",
      "images/activity-6/30.jpg",
      "images/activity-6/31.jpg",
      "images/activity-6/32.jpg",
      "images/activity-6/33.jpg",
      "images/activity-6/34.jpg",
      "images/activity-6/35.jpg",
      "images/activity-6/36.jpg",
      "images/activity-6/37.jpg",
      "images/activity-6/38.jpg",
      "images/activity-6/39.jpg",
      "images/activity-6/40.jpg",
      "images/activity-6/41.jpg",
      "images/activity-6/42.jpg",
      "images/activity-6/43.jpg",
      "images/activity-6/44.jpg",
      "images/activity-6/45.jpg",
      "images/activity-6/46.jpg",
      "images/activity-6/47.jpg",
      "images/activity-6/48.jpg",
      "images/activity-6/49.jpg",
      "images/activity-6/50.jpg",
      "images/activity-6/51.jpg",
      "images/activity-6/52.jpg",
      "images/activity-6/53.jpg",
      "images/activity-6/54.jpg",
      "images/activity-6/55.jpg",
      "images/activity-6/56.jpg",
      "images/activity-6/57.jpg",
      "images/activity-6/59.jpg",
      "images/activity-6/60.jpg",
      "images/activity-6/61.jpg",
      "images/activity-6/62.jpg",
      "images/activity-6/63.jpg",
      "images/activity-6/64.jpg",
      "images/activity-6/65.jpg",
      "images/activity-6/66.jpg",
      "images/activity-6/67.jpg",
      "images/activity-6/69.jpg",
      "images/activity-6/70.jpg",
      "images/activity-6/72.jpg",
      "images/activity-6/73.jpg"
    ],
    sections: [
      { type: "text", zh: "每一種語言，都開啟了一扇認識文化的大門。", en: "Every language opens the door to a new culture." },
      { type: "photos", items: ["images/activity-6/1.jpg", "images/activity-6/2.jpg", "images/activity-6/3.jpg", "images/activity-6/4.jpg", "images/activity-6/5.jpg", "images/activity-6/6.jpg", "images/activity-6/7.jpg", "images/activity-6/8.jpg", "images/activity-6/9.jpg", "images/activity-6/10.jpg", "images/activity-6/11.jpg", "images/activity-6/12.jpg", "images/activity-6/13.jpg", "images/activity-6/14.jpg"] },
      { type: "text", zh: "發現不同語言的共通點，讓學習更加有趣。", en: "Discovering similarities makes language learning more enjoyable." },
      { type: "photos", items: ["images/activity-6/15.jpg", "images/activity-6/16.jpg", "images/activity-6/17.jpg", "images/activity-6/18.jpg", "images/activity-6/19.jpg", "images/activity-6/20.jpg", "images/activity-6/21.jpg", "images/activity-6/22.jpg", "images/activity-6/23.jpg", "images/activity-6/24.jpg", "images/activity-6/25.jpg", "images/activity-6/27.jpg", "images/activity-6/28.jpg", "images/activity-6/29.jpg"] },
      { type: "text", zh: "每一個新單字，都連結著不同文化的人們。", en: "Every new word connects people across cultures." },
      { type: "photos", items: ["images/activity-6/30.jpg", "images/activity-6/31.jpg", "images/activity-6/32.jpg", "images/activity-6/33.jpg", "images/activity-6/34.jpg", "images/activity-6/35.jpg", "images/activity-6/36.jpg", "images/activity-6/37.jpg", "images/activity-6/38.jpg", "images/activity-6/39.jpg", "images/activity-6/40.jpg", "images/activity-6/41.jpg", "images/activity-6/42.jpg", "images/activity-6/43.jpg"] },
      { type: "text", zh: "一起學習不同語言，創造難忘的回憶。", en: "Learning languages together creates unforgettable moments." },
      { type: "photos", items: ["images/activity-6/44.jpg", "images/activity-6/45.jpg", "images/activity-6/46.jpg", "images/activity-6/47.jpg", "images/activity-6/48.jpg", "images/activity-6/49.jpg", "images/activity-6/50.jpg", "images/activity-6/51.jpg", "images/activity-6/52.jpg", "images/activity-6/53.jpg", "images/activity-6/54.jpg", "images/activity-6/55.jpg", "images/activity-6/56.jpg", "images/activity-6/57.jpg"] },
      { type: "text", zh: "不同的語言，共同的好奇心，無限的可能。", en: "Different languages, shared curiosity, endless possibilities." },
      { type: "photos", items: ["images/activity-6/59.jpg", "images/activity-6/60.jpg", "images/activity-6/61.jpg", "images/activity-6/62.jpg", "images/activity-6/63.jpg", "images/activity-6/64.jpg", "images/activity-6/65.jpg", "images/activity-6/66.jpg", "images/activity-6/67.jpg", "images/activity-6/69.jpg", "images/activity-6/70.jpg", "images/activity-6/72.jpg", "images/activity-6/73.jpg"] },
    ],
    videoUrls: []
  }
];

// 從 YouTube 網址取出影片 ID，支援 watch?v=、youtu.be/、embed/
function getYouTubeId(url) {
  const patterns = [
    /(?:youtube\.com\/watch\?v=)([^&]+)/,
    /(?:youtu\.be\/)([^?]+)/,
    /(?:youtube\.com\/embed\/)([^?]+)/
  ];
  for (const p of patterns) {
    const m = url.match(p);
    if (m) return m[1];
  }
  return null;
}
