// ============================================================
// 在這裡編輯你的活動內容 / Edit your activity content here
// ============================================================
//
// 【可選】想在照片中間穿插文字介紹，可以在任一活動物件裡加上
// "sections" 陣列，取代原本單純的照片牆。順序就是畫面上的順序，
// 文字段落跟照片群組可以自由交錯、重複幾次都可以。若不加這個欄
// 位，會照舊用 photos 陣列顯示成一整片照片牆。
//
// 格式範例（可直接複製貼到任一個活動物件裡，跟 photos 同一層）：
//
// sections: [
//   { type: "text", zh: "這裡放中文介紹段落。", en: "English intro paragraph here." },
//   { type: "photos", items: ["images/activity-1/1.jpg", "images/activity-1/2.jpg"] },
//   { type: "text", zh: "第二段文字，可以講活動的另一個環節。", en: "Second paragraph, e.g. about another part of the event." },
//   { type: "photos", items: ["images/activity-1/3.jpg", "images/activity-1/4.jpg", "images/activity-1/5.jpg"] }
// ],
//
// 只要照片檔名跟原本 images/activity-x/ 資料夾裡的一致即可，同一張
// 照片也可以分配到不同的 photos 群組裡，不用整批貼在一起。
//
// 【可選】想在頁面最上方（標題下方、照片牆之前）放一張置中的大合照
// （像首頁的精華影片那樣的明信片卡片樣式），在活動物件裡加上：
//
// groupPhoto: "images/activity-1/group.jpg",
//
// 把合照檔案放進對應的 images/activity-x/ 資料夾即可，檔名不限，
// 只要跟這裡填的路徑一致。不加這個欄位就不會顯示這個區塊。
// ============================================================

// 首頁主打影片的 YouTube 連結 (完整網址即可)
const HERO_VIDEO_URL = "https://www.youtube.com/watch?v=dQw4w9WgXcQ";

// 六場活動資料
const ACTIVITIES = [
  {
    id: 1,
    stamp: "NO. 01",
    date: "2026.03.12",
    titleZh: "大城市大冒險",
    titleEn: "Big City Adventure",
    descZh: "探索世界各地知名的城市。",
    descEn: "Discover famous cities from around the world.",
    cover: "images/activity-1/cover.jpg",
    groupPhoto: "images/activity-1/group.jpg",
    photos: [
      "images/activity-1/1.jpg",
      "images/activity-1/2.jpg",
      "images/activity-1/3.jpg",
      "images/activity-1/4.jpg",
      "images/activity-1/5.jpg",
      "images/activity-1/6.jpg",
      "images/activity-1/8.jpg",
      "images/activity-1/9.jpg",
      "images/activity-1/10.jpg",
      "images/activity-1/12.jpg",
      "images/activity-1/14.jpg",
      "images/activity-1/15.jpg",
      "images/activity-1/16.jpg",
      "images/activity-1/17.jpg",
      "images/activity-1/18.jpg",
      "images/activity-1/19.jpg",
      "images/activity-1/20.jpg",
      "images/activity-1/21.jpg",
      "images/activity-1/22.jpg",
      "images/activity-1/23.jpg",
      "images/activity-1/24.jpg"
    ],
    sections: [
      { type: "text", zh: "每個線索都通往一場新冒險。", en: "Every clue leads to a new adventure." },
      { type: "photos", items: ["images/activity-1/1.jpg", "images/activity-1/2.jpg", "images/activity-1/3.jpg", "images/activity-1/4.jpg", "images/activity-1/5.jpg", "images/activity-1/6.jpg"] },
      { type: "text", zh: "團隊合作讓每個挑戰更加刺激。", en: "Teamwork makes every challenge more exciting." },
      { type: "photos", items: ["images/activity-1/8.jpg", "images/activity-1/9.jpg", "images/activity-1/10.jpg", "images/activity-1/12.jpg"] },
      { type: "text", zh: "學英語也可以像一場旅行。", en: "Learning English can feel like traveling." },
      { type: "photos", items: ["images/activity-1/14.jpg", "images/activity-1/15.jpg", "images/activity-1/16.jpg", "images/activity-1/17.jpg", "images/activity-1/18.jpg", "images/activity-1/19.jpg"] },
      { type: "text", zh: "大城市、大夢想,還有更燦爛的笑容。", en: "Big cities, big dreams, and even bigger smiles." },
      { type: "photos", items: ["images/activity-1/20.jpg", "images/activity-1/21.jpg", "images/activity-1/22.jpg", "images/activity-1/23.jpg", "images/activity-1/24.jpg"] },
    ],
    videoUrls: []
  },
  {
    id: 2,
    stamp: "NO. 02",
    date: "2026.03.19",
    titleZh: "餅乾怪獸模式：啟動",
    titleEn: "Cookie Monster Mode: ON",
    descZh: "餅乾讓學習更添甜蜜。",
    descEn: "Cookies make learning extra sweet.",
    cover: "images/activity-2/cover.jpg",
    groupPhoto: "images/activity-2/group.jpg",
    photos: [
      "images/activity-2/1.jpg",
      "images/activity-2/3.jpg",
      "images/activity-2/4.jpg",
      "images/activity-2/5.jpg",
      "images/activity-2/6.jpg",
      "images/activity-2/7.jpg",
      "images/activity-2/8.jpg",
      "images/activity-2/9.jpg",
      "images/activity-2/10.jpg",
      "images/activity-2/12.jpg",
      "images/activity-2/13.jpg",
      "images/activity-2/14.jpg",
      "images/activity-2/15.jpg",
      "images/activity-2/16.jpg",
      "images/activity-2/17.jpg",
      "images/activity-2/18.jpg",
      "images/activity-2/20.jpg",
      "images/activity-2/21.jpg",
      "images/activity-2/22.jpg",
      "images/activity-2/23.jpg",
      "images/activity-2/25.jpg",
      "images/activity-2/26.jpg",
      "images/activity-2/28.jpg",
      "images/activity-2/30.jpg",
      "images/activity-2/31.jpg",
      "images/activity-2/32.jpg",
      "images/activity-2/33.jpg",
      "images/activity-2/34.jpg",
      "images/activity-2/35.jpg",
      "images/activity-2/36.jpg",
      "images/activity-2/37.jpg",
      "images/activity-2/38.jpg",
      "images/activity-2/39.jpg",
      "images/activity-2/40.jpg",
      "images/activity-2/41.jpg",
      "images/activity-2/42.jpg",
      "images/activity-2/43.jpg",
      "images/activity-2/44.jpg",
      "images/activity-2/45.jpg",
      "images/activity-2/47.jpg",
      "images/activity-2/48.jpg",
      "images/activity-2/50.jpg"
    ],
    sections: [
      { type: "text", zh: "每個遊戲都帶來新的美味驚喜。", en: "Every game brings another tasty surprise." },
      { type: "photos", items: ["images/activity-2/1.jpg", "images/activity-2/3.jpg", "images/activity-2/4.jpg", "images/activity-2/5.jpg", "images/activity-2/6.jpg", "images/activity-2/7.jpg", "images/activity-2/8.jpg", "images/activity-2/9.jpg", "images/activity-2/10.jpg", "images/activity-2/12.jpg", "images/activity-2/13.jpg"] },
      { type: "text", zh: "一口一口,練習英語。", en: "Practice English one bite at a time." },
      { type: "photos", items: ["images/activity-2/14.jpg", "images/activity-2/15.jpg", "images/activity-2/16.jpg", "images/activity-2/17.jpg", "images/activity-2/18.jpg", "images/activity-2/20.jpg", "images/activity-2/21.jpg", "images/activity-2/22.jpg", "images/activity-2/23.jpg", "images/activity-2/25.jpg", "images/activity-2/26.jpg"] },
      { type: "text", zh: "分享點心,也分享歡笑。", en: "Sharing snacks means sharing laughter." },
      { type: "photos", items: ["images/activity-2/28.jpg", "images/activity-2/30.jpg", "images/activity-2/31.jpg", "images/activity-2/32.jpg", "images/activity-2/33.jpg", "images/activity-2/34.jpg", "images/activity-2/35.jpg", "images/activity-2/36.jpg", "images/activity-2/37.jpg", "images/activity-2/38.jpg"] },
      { type: "text", zh: "甜蜜時光,成就難忘回憶。", en: "Sweet moments create unforgettable memories." },
      { type: "photos", items: ["images/activity-2/39.jpg", "images/activity-2/40.jpg", "images/activity-2/41.jpg", "images/activity-2/42.jpg", "images/activity-2/43.jpg", "images/activity-2/44.jpg", "images/activity-2/45.jpg", "images/activity-2/47.jpg", "images/activity-2/48.jpg", "images/activity-2/50.jpg"] },
    ],
    videoUrls: []
  },
  {
    id: 3,
    stamp: "NO. 03",
    date: "2026.04.23",
    titleZh: "從台灣與美國的日常標誌與廣告學英文",
    titleEn: "English through Everyday Signs and Ads in Taiwan and the USA",
    descZh: "英語就藏在我們生活的每個角落。",
    descEn: "English is everywhere around us.",
    cover: "images/activity-3/cover.jpg",
    groupPhoto: "images/activity-3/group.jpg",
    photos: [
      "images/activity-3/1.jpg",
      "images/activity-3/2.jpg",
      "images/activity-3/3.jpg",
      "images/activity-3/4.jpg",
      "images/activity-3/5.jpg",
      "images/activity-3/6.jpg",
      "images/activity-3/7.jpg",
      "images/activity-3/8.jpg",
      "images/activity-3/9.jpg",
      "images/activity-3/10.jpg",
      "images/activity-3/11.jpg",
      "images/activity-3/12.jpg",
      "images/activity-3/13.jpg",
      "images/activity-3/14.jpg",
      "images/activity-3/15.jpg",
      "images/activity-3/16.jpg",
      "images/activity-3/17.jpg",
      "images/activity-3/18.jpg",
      "images/activity-3/19.jpg",
      "images/activity-3/20.jpg",
      "images/activity-3/21.jpg",
      "images/activity-3/22.jpg",
      "images/activity-3/23.jpg",
      "images/activity-3/24.jpg",
      "images/activity-3/25.jpg",
      "images/activity-3/26.jpg",
      "images/activity-3/27.jpg",
      "images/activity-3/28.jpg",
      "images/activity-3/29.jpg",
      "images/activity-3/30.jpg",
      "images/activity-3/31.jpg",
      "images/activity-3/32.jpg",
      "images/activity-3/33.jpg",
      "images/activity-3/34.jpg",
      "images/activity-3/35.jpg",
      "images/activity-3/36.jpg",
      "images/activity-3/37.jpg",
      "images/activity-3/38.jpg",
      "images/activity-3/39.jpg",
      "images/activity-3/40.jpg"
    ],
    sections: [
      { type: "text", zh: "日常標誌訴說著有趣的故事。", en: "Everyday signs tell interesting stories." },
      { type: "photos", items: ["images/activity-3/1.jpg", "images/activity-3/2.jpg", "images/activity-3/3.jpg", "images/activity-3/4.jpg", "images/activity-3/5.jpg", "images/activity-3/6.jpg", "images/activity-3/7.jpg", "images/activity-3/8.jpg", "images/activity-3/9.jpg", "images/activity-3/10.jpg"] },
      { type: "text", zh: "小小的字詞,也能藏著大大的意義。", en: "Small words can have big meanings." },
      { type: "photos", items: ["images/activity-3/11.jpg", "images/activity-3/12.jpg", "images/activity-3/13.jpg", "images/activity-3/14.jpg", "images/activity-3/15.jpg", "images/activity-3/16.jpg", "images/activity-3/17.jpg", "images/activity-3/18.jpg", "images/activity-3/19.jpg", "images/activity-3/20.jpg"] },
      { type: "text", zh: "透過日常語言,比較不同文化。", en: "Compare cultures through everyday language." },
      { type: "photos", items: ["images/activity-3/21.jpg", "images/activity-3/22.jpg", "images/activity-3/23.jpg", "images/activity-3/24.jpg", "images/activity-3/25.jpg", "images/activity-3/26.jpg", "images/activity-3/27.jpg", "images/activity-3/28.jpg", "images/activity-3/29.jpg", "images/activity-3/30.jpg"] },
      { type: "text", zh: "學習,從簡單的觀察開始。", en: "Learning starts with simple observations." },
      { type: "photos", items: ["images/activity-3/31.jpg", "images/activity-3/32.jpg", "images/activity-3/33.jpg", "images/activity-3/34.jpg", "images/activity-3/35.jpg", "images/activity-3/36.jpg", "images/activity-3/37.jpg", "images/activity-3/38.jpg", "images/activity-3/39.jpg", "images/activity-3/40.jpg"] },
    ],
    videoUrls: []
  },
  {
    id: 4,
    stamp: "NO. 04",
    date: "2026.04.29",
    titleZh: "從頭到腳：透過身體部位玩英語慣用語",
    titleEn: "From Head to Toe: Having Fun with English Idioms Through Body Parts",
    descZh: "慣用語讓英語變得生動又有趣。",
    descEn: "Idioms make English fun and colorful.",
    cover: "images/activity-4/cover.jpg",
    groupPhoto: "images/activity-4/group.jpg",
    photos: [
      "images/activity-4/1.jpg",
      "images/activity-4/2.jpg",
      "images/activity-4/3.jpg",
      "images/activity-4/4.jpg",
      "images/activity-4/5.jpg",
      "images/activity-4/6.jpg",
      "images/activity-4/7.jpg",
      "images/activity-4/8.jpg",
      "images/activity-4/9.jpg",
      "images/activity-4/10.jpg",
      "images/activity-4/11.jpg",
      "images/activity-4/12.jpg",
      "images/activity-4/13.jpg",
      "images/activity-4/14.jpg",
      "images/activity-4/15.jpg",
      "images/activity-4/16.jpg",
      "images/activity-4/17.jpg",
      "images/activity-4/19.jpg",
      "images/activity-4/20.jpg",
      "images/activity-4/21.jpg",
      "images/activity-4/22.jpg",
      "images/activity-4/23.jpg",
      "images/activity-4/25.jpg",
      "images/activity-4/26.jpg",
      "images/activity-4/27.jpg",
      "images/activity-4/29.jpg",
      "images/activity-4/30.jpg",
      "images/activity-4/31.jpg",
      "images/activity-4/32.jpg",
      "images/activity-4/33.jpg",
      "images/activity-4/34.jpg",
      "images/activity-4/36.jpg",
      "images/activity-4/37.jpg",
      "images/activity-4/38.jpg",
      "images/activity-4/39.jpg",
      "images/activity-4/40.jpg",
      "images/activity-4/41.jpg",
      "images/activity-4/42.jpg",
      "images/activity-4/43.jpg",
      "images/activity-4/44.jpg",
      "images/activity-4/46.jpg",
      "images/activity-4/47.jpg",
      "images/activity-4/48.jpg",
      "images/activity-4/50.jpg",
      "images/activity-4/51.jpg",
      "images/activity-4/52.jpg",
      "images/activity-4/53.jpg",
      "images/activity-4/54.jpg",
      "images/activity-4/58.jpg",
      "images/activity-4/60.jpg",
      "images/activity-4/61.jpg",
      "images/activity-4/62.jpg",
      "images/activity-4/63.jpg",
      "images/activity-4/65.jpg",
      "images/activity-4/66.jpg",
      "images/activity-4/67.jpg",
      "images/activity-4/68.jpg",
      "images/activity-4/69.jpg",
      "images/activity-4/70.jpg",
      "images/activity-4/71.jpg",
      "images/activity-4/72.jpg",
      "images/activity-4/73.jpg",
      "images/activity-4/74.jpg",
      "images/activity-4/75.jpg",
      "images/activity-4/76.jpg",
      "images/activity-4/77.jpg",
      "images/activity-4/78.jpg",
      "images/activity-4/80.jpg"
    ],
    sections: [
      { type: "text", zh: "身體部位也能說出有趣的故事。", en: "Body parts can tell funny stories." },
      { type: "photos", items: ["images/activity-4/1.jpg", "images/activity-4/2.jpg", "images/activity-4/3.jpg", "images/activity-4/4.jpg", "images/activity-4/5.jpg", "images/activity-4/6.jpg", "images/activity-4/7.jpg", "images/activity-4/8.jpg", "images/activity-4/9.jpg", "images/activity-4/10.jpg", "images/activity-4/11.jpg", "images/activity-4/12.jpg", "images/activity-4/13.jpg", "images/activity-4/14.jpg", "images/activity-4/15.jpg", "images/activity-4/16.jpg", "images/activity-4/17.jpg", "images/activity-4/19.jpg", "images/activity-4/20.jpg"] },
      { type: "text", zh: "一起猜、一起笑、一起學。", en: "Guess, laugh, and learn together." },
      { type: "photos", items: ["images/activity-4/21.jpg", "images/activity-4/22.jpg", "images/activity-4/23.jpg", "images/activity-4/25.jpg", "images/activity-4/26.jpg", "images/activity-4/27.jpg", "images/activity-4/29.jpg", "images/activity-4/30.jpg", "images/activity-4/31.jpg", "images/activity-4/32.jpg", "images/activity-4/33.jpg", "images/activity-4/34.jpg", "images/activity-4/36.jpg", "images/activity-4/37.jpg", "images/activity-4/38.jpg", "images/activity-4/39.jpg"] },
      { type: "text", zh: "每句慣用語都藏著弦外之音。", en: "Every expression has a hidden meaning." },
      { type: "photos", items: ["images/activity-4/40.jpg", "images/activity-4/41.jpg", "images/activity-4/42.jpg", "images/activity-4/43.jpg", "images/activity-4/44.jpg", "images/activity-4/46.jpg", "images/activity-4/47.jpg", "images/activity-4/48.jpg", "images/activity-4/50.jpg", "images/activity-4/51.jpg", "images/activity-4/52.jpg", "images/activity-4/53.jpg", "images/activity-4/54.jpg", "images/activity-4/58.jpg", "images/activity-4/60.jpg", "images/activity-4/61.jpg"] },
      { type: "text", zh: "用日常慣用語,說出自然道地的英語。", en: "Speak naturally with everyday idioms." },
      { type: "photos", items: ["images/activity-4/62.jpg", "images/activity-4/63.jpg", "images/activity-4/65.jpg", "images/activity-4/66.jpg", "images/activity-4/67.jpg", "images/activity-4/68.jpg", "images/activity-4/69.jpg", "images/activity-4/70.jpg", "images/activity-4/71.jpg", "images/activity-4/72.jpg", "images/activity-4/73.jpg", "images/activity-4/74.jpg", "images/activity-4/75.jpg", "images/activity-4/76.jpg", "images/activity-4/77.jpg", "images/activity-4/78.jpg", "images/activity-4/80.jpg"] },
    ],
    videoUrls: []
  },
  {
    id: 5,
    stamp: "NO. 05",
    date: "2026.05.07",
    titleZh: "跨越文化：一位南非人在台灣",
    titleEn: "Crossing Cultures: A South African in Taiwan",
    descZh: "每個文化都有獨一無二的故事。",
    descEn: "Every culture has a unique story.",
    cover: "images/activity-5/cover.jpg",
    groupPhoto: "images/activity-5/group.jpg",
    photos: [
      "images/activity-5/1.jpg",
      "images/activity-5/2.jpg",
      "images/activity-5/3.jpg",
      "images/activity-5/4.jpg",
      "images/activity-5/5.jpg",
      "images/activity-5/6.jpg",
      "images/activity-5/7.jpg",
      "images/activity-5/8.jpg",
      "images/activity-5/9.jpg",
      "images/activity-5/10.jpg",
      "images/activity-5/11.jpg",
      "images/activity-5/12.jpg",
      "images/activity-5/13.jpg",
      "images/activity-5/14.jpg",
      "images/activity-5/15.jpg",
      "images/activity-5/16.jpg",
      "images/activity-5/17.jpg",
      "images/activity-5/18.jpg",
      "images/activity-5/19.jpg",
      "images/activity-5/20.jpg",
      "images/activity-5/21.jpg",
      "images/activity-5/22.jpg",
      "images/activity-5/23.jpg",
      "images/activity-5/24.jpg",
      "images/activity-5/25.jpg"
    ],
    sections: [
      { type: "text", zh: "不同的背景,讓友誼更加深厚。", en: "Different backgrounds build stronger friendships." },
      { type: "photos", items: ["images/activity-5/1.jpg", "images/activity-5/2.jpg", "images/activity-5/3.jpg", "images/activity-5/4.jpg", "images/activity-5/5.jpg", "images/activity-5/6.jpg", "images/activity-5/7.jpg"] },
      { type: "text", zh: "用嶄新的視角認識台灣。", en: "Discover Taiwan through fresh perspectives." },
      { type: "photos", items: ["images/activity-5/8.jpg", "images/activity-5/9.jpg", "images/activity-5/10.jpg", "images/activity-5/11.jpg", "images/activity-5/12.jpg", "images/activity-5/13.jpg"] },
      { type: "text", zh: "好奇心,是理解世界的第一步。", en: "Curiosity opens the door to understanding." },
      { type: "photos", items: ["images/activity-5/14.jpg", "images/activity-5/15.jpg", "images/activity-5/16.jpg", "images/activity-5/17.jpg", "images/activity-5/18.jpg", "images/activity-5/19.jpg"] },
      { type: "text", zh: "語言,連結起世界各地的人們。", en: "Language connects people across the world." },
      { type: "photos", items: ["images/activity-5/20.jpg", "images/activity-5/21.jpg", "images/activity-5/22.jpg", "images/activity-5/23.jpg", "images/activity-5/24.jpg", "images/activity-5/25.jpg"] },
    ],
    videoUrls: []
  },
  {
    id: 6,
    stamp: "NO. 06",
    date: "2026.05.14",
    titleZh: "「字彙」三角：英語 X 日語 X 韓語",
    titleEn: "A \"Vocabulary\" Triangle: English X 日本語 X 한국어",
    descZh: "三種語言,一場精彩的體驗。",
    descEn: "Three languages, one amazing experience.",
    cover: "images/activity-6/cover.jpg",
    groupPhoto: "images/activity-6/group.jpg",
    photos: [
      "images/activity-6/1.jpg",
      "images/activity-6/2.jpg",
      "images/activity-6/3.jpg",
      "images/activity-6/4.jpg",
      "images/activity-6/5.jpg",
      "images/activity-6/6.jpg",
      "images/activity-6/7.jpg",
      "images/activity-6/8.jpg",
      "images/activity-6/9.jpg",
      "images/activity-6/10.jpg",
      "images/activity-6/11.jpg",
      "images/activity-6/12.jpg",
      "images/activity-6/13.jpg",
      "images/activity-6/14.jpg",
      "images/activity-6/15.jpg",
      "images/activity-6/16.jpg",
      "images/activity-6/17.jpg",
      "images/activity-6/18.jpg",
      "images/activity-6/19.jpg",
      "images/activity-6/20.jpg",
      "images/activity-6/21.jpg",
      "images/activity-6/22.jpg",
      "images/activity-6/23.jpg",
      "images/activity-6/24.jpg",
      "images/activity-6/25.jpg",
      "images/activity-6/27.jpg",
      "images/activity-6/28.jpg",
      "images/activity-6/29.jpg",
      "images/activity-6/30.jpg",
      "images/activity-6/31.jpg",
      "images/activity-6/32.jpg",
      "images/activity-6/33.jpg",
      "images/activity-6/34.jpg",
      "images/activity-6/35.jpg",
      "images/activity-6/36.jpg",
      "images/activity-6/37.jpg",
      "images/activity-6/38.jpg",
      "images/activity-6/39.jpg",
      "images/activity-6/40.jpg",
      "images/activity-6/41.jpg",
      "images/activity-6/42.jpg",
      "images/activity-6/43.jpg",
      "images/activity-6/44.jpg",
      "images/activity-6/45.jpg",
      "images/activity-6/46.jpg",
      "images/activity-6/47.jpg",
      "images/activity-6/48.jpg",
      "images/activity-6/49.jpg",
      "images/activity-6/50.jpg",
      "images/activity-6/51.jpg",
      "images/activity-6/52.jpg",
      "images/activity-6/53.jpg",
      "images/activity-6/54.jpg",
      "images/activity-6/55.jpg",
      "images/activity-6/56.jpg",
      "images/activity-6/57.jpg",
      "images/activity-6/59.jpg",
      "images/activity-6/60.jpg",
      "images/activity-6/61.jpg",
      "images/activity-6/62.jpg",
      "images/activity-6/63.jpg",
      "images/activity-6/64.jpg",
      "images/activity-6/65.jpg",
      "images/activity-6/66.jpg",
      "images/activity-6/67.jpg",
      "images/activity-6/69.jpg",
      "images/activity-6/70.jpg",
      "images/activity-6/72.jpg",
      "images/activity-6/73.jpg"
    ],
    sections: [
      { type: "text", zh: "發現不同文化之間的相似之處。", en: "Discover similarities across different cultures." },
      { type: "photos", items: ["images/activity-6/1.jpg", "images/activity-6/2.jpg", "images/activity-6/3.jpg", "images/activity-6/4.jpg", "images/activity-6/5.jpg", "images/activity-6/6.jpg", "images/activity-6/7.jpg", "images/activity-6/8.jpg", "images/activity-6/9.jpg", "images/activity-6/10.jpg", "images/activity-6/11.jpg", "images/activity-6/12.jpg", "images/activity-6/13.jpg", "images/activity-6/14.jpg", "images/activity-6/15.jpg", "images/activity-6/16.jpg", "images/activity-6/17.jpg", "images/activity-6/18.jpg"] },
      { type: "text", zh: "每個新單字,都打開一個新世界。", en: "Every new word opens a new world." },
      { type: "photos", items: ["images/activity-6/19.jpg", "images/activity-6/20.jpg", "images/activity-6/21.jpg", "images/activity-6/22.jpg", "images/activity-6/23.jpg", "images/activity-6/24.jpg", "images/activity-6/25.jpg", "images/activity-6/27.jpg", "images/activity-6/28.jpg", "images/activity-6/29.jpg", "images/activity-6/30.jpg", "images/activity-6/31.jpg", "images/activity-6/32.jpg", "images/activity-6/33.jpg", "images/activity-6/34.jpg", "images/activity-6/35.jpg", "images/activity-6/36.jpg"] },
      { type: "text", zh: "一起學習,讓語言不再困難。", en: "Learning together makes languages easier." },
      { type: "photos", items: ["images/activity-6/37.jpg", "images/activity-6/38.jpg", "images/activity-6/39.jpg", "images/activity-6/40.jpg", "images/activity-6/41.jpg", "images/activity-6/42.jpg", "images/activity-6/43.jpg", "images/activity-6/44.jpg", "images/activity-6/45.jpg", "images/activity-6/46.jpg", "images/activity-6/47.jpg", "images/activity-6/48.jpg", "images/activity-6/49.jpg", "images/activity-6/50.jpg", "images/activity-6/51.jpg", "images/activity-6/52.jpg", "images/activity-6/53.jpg", "images/activity-6/54.jpg"] },
      { type: "text", zh: "語言不同,笑容卻相同。", en: "Different languages, shared smiles." },
      { type: "photos", items: ["images/activity-6/55.jpg", "images/activity-6/56.jpg", "images/activity-6/57.jpg", "images/activity-6/59.jpg", "images/activity-6/60.jpg", "images/activity-6/61.jpg", "images/activity-6/62.jpg", "images/activity-6/63.jpg", "images/activity-6/64.jpg", "images/activity-6/65.jpg", "images/activity-6/66.jpg", "images/activity-6/67.jpg", "images/activity-6/69.jpg", "images/activity-6/70.jpg", "images/activity-6/72.jpg", "images/activity-6/73.jpg"] },
    ],
    videoUrls: []
  }
];

// 從 YouTube 網址取出影片 ID，支援 watch?v=、youtu.be/、embed/
function getYouTubeId(url) {
  const patterns = [
    /(?:youtube\.com\/watch\?v=)([^&]+)/,
    /(?:youtu\.be\/)([^?]+)/,
    /(?:youtube\.com\/embed\/)([^?]+)/
  ];
  for (const p of patterns) {
    const m = url.match(p);
    if (m) return m[1];
  }
  return null;
}
